import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
function TopNav()
{
  return (
    <div>
      <nav className="flex justify-between border-b w-full p-5 text-xl font-bold">
        <div>Gallery</div>
        <div>Sign in</div>
      </nav>

    </div>
  )
}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
      <TopNav></TopNav>
      
      {children}</body>
    </html>
  );
}
